### ISSUE TITLE
Error:Execution failed for task ':app:dexDebug'.

### ISSUE THREAD

**Issue by kelvinji2009** [virl/underdark-android#1]
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_65.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

------------------
./gradlew build --debug
------------------
...
processing io/netty/util/concurrent/MultithreadEventExecutorGroup.class...

18:09:34.357 [ERROR] [org.gradle.api.Project] EXCEPTION FROM SIMULATION:
local variable type mismatch: attempt to set or access a value of type java.lang.Object using a local variable of type int. This is symptomatic of .class transformation tools that ignore local variable information.
...at bytecode offset 000000a9
locals[0000]: Lio/netty/util/concurrent/MultithreadEventExecutorGroup;
locals[0001]: I
locals[0002]: Ljava/lang/Object;
locals[0003]: [Ljava/lang/Object;
locals[0004]: I
stack[top0]: type{java.lang.Object}
...while working on block 00a9
...while working on method <init>:(ILjava/util/concurrent/Executor;[Ljava/lang/Object;)V
...while processing <init> (ILjava/util/concurrent/Executor;[Ljava/lang/Object;)V
...while processing io/netty/util/concurrent/MultithreadEventExecutorGroup.class
1 error; aborting

18:09:34.358 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':app:preDexDebug'
18:09:34.358 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :app:preDexDebug FAILED
18:09:34.359 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:preDexDebug (Thread[main,5,main]) completed. Took 9.047 secs.
18:09:34.359 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 9.598 secs, idle: 0.011 secs
18:09:34.365 [ERROR] [org.gradle.BuildExceptionReporter]
18:09:34.365 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
18:09:34.365 [ERROR] [org.gradle.BuildExceptionReporter]
18:09:34.365 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
18:09:34.365 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':app:preDexDebug'.
18:09:34.366 [ERROR] [org.gradle.BuildExceptionReporter] > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_65.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
18:09:34.366 [ERROR] [org.gradle.BuildExceptionReporter]
18:09:34.366 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
18:09:34.366 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
18:09:34.367 [LIFECYCLE] [org.gradle.BuildResultLogger]
18:09:34.367 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
...

**Comment by kelvinji2009** [comment]
if back to compile 'io.underdark:underdark:1.0.3', work fine.

**Comment by virl** [comment]
@kelvinji2009 Thanks, I will look into it.

**Comment by virl** [comment]
@kelvinji2009 Can you please send me your app project? Or, if it's not possible, can you please send me Proguard settings (proguard-rules.pro) and Gradle scripts?

**Comment by virl** [comment]
@kelvinji2009 I've tested published new version 1.0.6 — please try it and tell me have it fixed that issue for you.

**Comment by kelvinji2009** [comment]
@virl Already fixed and thank you. BTW, i think you'd better ignore .idea and *.iml.

**Comment by virl** [comment]
@kelvinji2009 Why ignore .iml? It's just computer-independent idea project file.

Also, I'll be glad if you tell me in what kind of project want to use this library. You can contact me privately at virlof@gmail.com
